#!/bin/bash
#awk '{print substr($0,index($0," | ")+3)}' $BARTIB_FILE  \
#	| uniq \
#	| fzf \
#	| cat 

bartib last \
	| tail -n +3 \
	| head -n -1 \
	| fzf \
	| grep -Po "(?<=\[)[^\[]+(?=\])" \
	| bartib continue
