require("config.autopairs")
require("config.compe")
require("config.dap")
require("config.icons")
require("config.lsp")
require("config.lualine")
require("config.telescope")
require("config.treesitter")
